"""Remote Streamable HTTP MCP endpoint for OpenClaw.

This is a deliberately small, dependency-free resource server.  It reuses the
existing :class:`~integrations.openclaw_mcp.server.McpServer` JSON-RPC/tool
implementation and sends every tool call through an operator-supplied
AgentGuard ``invoke`` callable.  The callable is always invoked with
``authorization_header=None``: an external OAuth access token is used only to
derive a verified subject and is never forwarded to a business endpoint.

The class is suitable for local tests and for embedding behind a TLS reverse
proxy.  It does not pretend to terminate TLS itself; a public deployment must
put it behind HTTPS/mTLS and configure a real OIDC verifier and audit sink.
"""

from __future__ import annotations

import contextvars
import copy
import ipaddress
import inspect
import json
import re
import secrets
import threading
import time
import uuid
from collections import defaultdict, deque
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FutureTimeoutError
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Callable, IO, Mapping
from urllib.parse import urlsplit

from .agentguard_client import AgentGuardClientError
from .auth import (
    AuthenticatedPrincipal,
    McpAuthenticationError,
    McpAuthenticator,
    protected_resource_metadata,
    validate_https_endpoint,
)
from .server import McpServer, SUPPORTED_PROTOCOL_VERSIONS


MCP_PATH = "/mcp"
MAX_REQUEST_BYTES = 1024 * 1024
DEFAULT_MAX_RESPONSE_BYTES = 1024 * 1024
_REQUEST_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._~:-]{0,127}$")


def _is_loopback_host(host: str) -> bool:
    """Return whether *host* is an explicitly loopback listener address.

    Do not resolve arbitrary DNS names here: a hostname that resolves to a
    loopback address today may resolve to a public address later (or vice
    versa).  Operators who need a remote listener must explicitly declare
    that TLS is terminated by a trusted reverse proxy.
    """

    candidate = str(host or "").strip().lower().rstrip(".")
    if candidate == "localhost":
        return True
    try:
        return ipaddress.ip_address(candidate).is_loopback
    except ValueError:
        return False


def _validated_request_id(value: Any, *, supplied_by_header: bool = False) -> str:
    """Validate an audit/request correlation id without allowing log injection."""

    if value is None or value == "":
        return f"mcp-http-{uuid.uuid4().hex}"
    if isinstance(value, bool):
        candidate = ""
    elif isinstance(value, (str, int, float)):
        candidate = str(value).strip()
    else:
        candidate = ""
    if not candidate or not _REQUEST_ID_RE.fullmatch(candidate):
        if supplied_by_header:
            raise RemoteMcpError(
                "MCP_H_REQUEST_ID_INVALID",
                "X-Request-ID 格式无效",
                status_code=400,
            )
        # JSON-RPC permits only string/number ids.  For an implementation
        # that receives a non-conforming id, preserve protocol handling while
        # using a fresh safe id for downstream audit correlation.
        return f"mcp-http-{uuid.uuid4().hex}"
    return candidate


def _principal_matches(left: AuthenticatedPrincipal, right: AuthenticatedPrincipal) -> bool:
    """Compare all authorization-relevant principal attributes for a session."""

    return (
        left.subject == right.subject
        and left.client_id == right.client_id
        and left.scopes == right.scopes
    )


class RemoteMcpError(RuntimeError):
    """A safe HTTP-level error generated by the remote MCP adapter."""

    def __init__(self, code: str, message: str, *, status_code: int = 400) -> None:
        super().__init__(message)
        self.code = code
        self.status_code = status_code


@dataclass
class _Session:
    principal: AuthenticatedPrincipal
    server: McpServer
    created_at: float
    last_seen: float


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


def _normalize_origin(origin: str) -> str:
    """Normalize an Origin value without accepting paths, credentials, or null."""

    value = origin.strip()
    parsed = urlsplit(value)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        return ""
    if parsed.username or parsed.password or parsed.path not in {"", "/"} or parsed.query or parsed.fragment:
        return ""
    host = parsed.hostname.lower()
    host_display = f"[{host}]" if ":" in host else host
    try:
        port = parsed.port
    except ValueError:
        return ""
    default_port = (parsed.scheme == "http" and port == 80) or (parsed.scheme == "https" and port == 443)
    netloc = host_display if port is None or default_port else f"{host_display}:{port}"
    return f"{parsed.scheme}://{netloc}"


def _session_header(value: str | None) -> str | None:
    if not value:
        return None
    candidate = value.strip()
    if not 8 <= len(candidate) <= 256:
        raise RemoteMcpError("MCP_H_SESSION_INVALID", "MCP 会话标识无效", status_code=400)
    if not all(ord(char) < 128 and (char.isalnum() or char in "._~-") for char in candidate):
        raise RemoteMcpError("MCP_H_SESSION_INVALID", "MCP 会话标识无效", status_code=400)
    return candidate


class RemoteAgentGuardClient:
    """AgentGuard client bound to one verified principal/session.

    ``backend`` must expose ``invoke(request, authorization_header)`` (for
    example :class:`service.AgentGuardService`) or be a callable with that
    signature.  The second argument is deliberately always ``None``.
    """

    def __init__(
        self,
        backend: Any,
        principal: AuthenticatedPrincipal,
        *,
        audit_sink: Callable[[Mapping[str, Any]], None] | Any | None = None,
        request_timeout_seconds: float = 8.0,
    ) -> None:
        self.backend = backend
        self.principal = principal
        self.audit_sink = audit_sink
        self.request_timeout_seconds = max(0.1, float(request_timeout_seconds))
        self._request_context: contextvars.ContextVar[dict[str, str]] = contextvars.ContextVar(
            "mcp_request_context", default={}
        )

    @contextmanager
    def request_context(self, request_id: str) -> Any:
        token = self._request_context.set({"request_id": request_id})
        try:
            yield
        finally:
            self._request_context.reset(token)

    def _audit(self, event: Mapping[str, Any]) -> None:
        if self.audit_sink is None:
            return
        writer = getattr(self.audit_sink, "write", None)
        if callable(writer):
            writer(dict(event))
            return
        if callable(self.audit_sink):
            self.audit_sink(dict(event))
            return
        raise RuntimeError("invalid audit sink")

    def _audit_event(
        self,
        *,
        request_id: str,
        opa_decision: str,
        reason_code: str,
        result_status: str,
        stage: str,
    ) -> dict[str, Any]:
        return {
            "event": "mcp_remote_enforcement",
            "stage": stage,
            "timestamp": _utc_now(),
            "request_id": request_id,
            "subject_id": self.principal.subject_id,
            "session_id": self.principal.session_id,
            "client_id": self.principal.client_id,
            "tool": "list_notices",
            "operation": "query",
            "agentguard_tool": "database.query",
            "opa_decision": opa_decision,
            "reason_code": reason_code,
            "result_status": result_status,
            "token_recorded": False,
        }

    def _request_payload(self, limit: int) -> dict[str, Any]:
        context = self._request_context.get()
        request_id = context.get("request_id") or f"mcp-http-{uuid.uuid4().hex}"
        now = _utc_now()
        return {
            "request_id": request_id,
            "task_id": f"mcp-task-{uuid.uuid4().hex}",
            "timestamp": now,
            # This object came from a verified JWT.  Never accept a subject
            # supplied in JSON-RPC params or a prompt.
            "subject": copy.deepcopy(self.principal.subject),
            "action": {
                "tool": "database.query",
                "operation": "query",
                "resource": "db://public/notices",
                "parameters": {"limit": limit, "item_count": limit},
                "risk_level": "low",
                "data_level": "internal",
            },
            "context": {
                "source": "mcp",
                "server_time": now,
                "destination_zone": "internal",
                "enforcement_point": "gateway",
                "mcp_adapter": "agentguard-openclaw-remote-http",
                "session_id": self.principal.session_id,
                "client_id": self.principal.client_id,
                "business_hours": True,
                "repeat_count": 0,
            },
            "environment": {"sandbox": {"enabled": False, "profile": ""}},
            "approval": {},
        }

    def _invoke_backend(self, payload: Mapping[str, Any]) -> dict[str, Any]:
        # The embedded AgentGuard service exposes an explicit verified-identity
        # boundary.  Prefer it whenever available so the remote path cannot be
        # mistaken for the legacy ``invoke(payload, None)`` adapter contract.
        verified_invoke = getattr(self.backend, "invoke_verified", None)
        if callable(verified_invoke):
            try:
                signature = inspect.signature(verified_invoke)
                signature.bind(
                    payload,
                    self.principal.subject,
                    session_id=self.principal.session_id,
                    client_id=self.principal.client_id,
                )
            except (TypeError, ValueError) as exc:
                raise AgentGuardClientError(
                    "MCP_G002_AGENTGUARD_UNAVAILABLE", "AgentGuard 已验证身份接口签名无效"
                ) from exc
            result = verified_invoke(
                payload,
                # Do not give the backend a mutable reference to the
                # session-bound principal.  A custom embedding backend must
                # not be able to rewrite the identity that future requests
                # are compared against.
                copy.deepcopy(self.principal.subject),
                session_id=self.principal.session_id,
                client_id=self.principal.client_id,
            )
            if not isinstance(result, Mapping):
                raise AgentGuardClientError("MCP_G005_INVALID_RESPONSE", "AgentGuard 响应必须是 JSON 对象")
            normalized = dict(result)
            normalized.setdefault("_agentguard_http_status", normalized.get("http_status", 200))
            return normalized

        invoke = getattr(self.backend, "invoke", None)
        if not callable(invoke):
            if not callable(self.backend):
                raise AgentGuardClientError("MCP_G002_AGENTGUARD_UNAVAILABLE", "AgentGuard 后端不可用")
            invoke = self.backend
        # Never pass the external OAuth token.  A direct embedded service can
        # use the already verified subject; a split deployment should exchange
        # it for a short-lived internal assertion before this boundary.
        # The production contract is ``invoke(request, authorization_header)``.
        # A one-argument callable is also accepted for small embedding/test
        # doubles, but signature inspection happens before invocation so a
        # TypeError raised *inside* a backend is never mistaken for arity and
        # retried (which could duplicate a side effect).
        try:
            signature = inspect.signature(invoke)
        except (TypeError, ValueError):
            signature = None
        if signature is not None:
            try:
                signature.bind(payload, None)
            except TypeError:
                try:
                    signature.bind(payload)
                except TypeError as exc:
                    raise AgentGuardClientError(
                        "MCP_G002_AGENTGUARD_UNAVAILABLE", "AgentGuard 后端接口签名无效"
                    ) from exc
                result = invoke(payload)
            else:
                result = invoke(payload, None)
        else:
            result = invoke(payload, None)
        if not isinstance(result, Mapping):
            raise AgentGuardClientError("MCP_G005_INVALID_RESPONSE", "AgentGuard 响应必须是 JSON 对象")
        normalized = dict(result)
        normalized.setdefault("_agentguard_http_status", normalized.get("http_status", 200))
        return normalized

    def list_notices(self, limit: int) -> dict[str, Any]:
        if isinstance(limit, bool) or not isinstance(limit, int) or not 1 <= limit <= 100:
            raise AgentGuardClientError("MCP_G001_ARGUMENT_INVALID", "limit 必须是 1 到 100 的整数")
        payload = self._request_payload(limit)
        request_id = str(payload["request_id"])
        # The preflight entry makes an unavailable audit sink fail closed before
        # the backend is touched.  The final entry records the OPA/result state.
        try:
            self._audit(
                self._audit_event(
                    request_id=request_id,
                    opa_decision="not_evaluated",
                    reason_code="MCP_AUDIT_PRECHECK",
                    result_status="pending",
                    stage="preflight",
                )
            )
        except Exception as exc:
            raise AgentGuardClientError("MCP_AUDIT_UNAVAILABLE", "安全审计不可用，调用未执行") from exc

        try:
            result = self._invoke_backend(payload)
        except AgentGuardClientError:
            raise
        except Exception as exc:
            raise AgentGuardClientError("MCP_G002_AGENTGUARD_UNAVAILABLE", "AgentGuard 调用未执行") from exc

        status = str(result.get("status", "blocked"))
        reason_code = str(result.get("reason_code", "MCP_G006_UNSAFE_RESPONSE"))
        opa_decision = str(result.get("policy_effect", "allow" if status == "executed_isolated" else "deny"))
        try:
            self._audit(
                self._audit_event(
                    request_id=request_id,
                    opa_decision=opa_decision,
                    reason_code=reason_code,
                    result_status=status,
                    stage="result",
                )
            )
        except Exception as exc:
            # Do not return business rows if the result cannot be audited.
            return {
                "status": "blocked",
                "http_status": 503,
                "_agentguard_http_status": 503,
                "reason_code": "MCP_AUDIT_UNAVAILABLE",
                "receipt": None,
            }
        return result


class StreamableHttpMcpServer:
    """Threaded Streamable HTTP MCP server with OIDC and origin enforcement."""

    def __init__(
        self,
        backend: Any,
        authenticator: McpAuthenticator,
        *,
        host: str = "127.0.0.1",
        port: int = 0,
        resource_url: str = "https://mcp.example.invalid/mcp",
        authorization_servers: tuple[str, ...] = (),
        allowed_origins: tuple[str, ...] = (),
        require_origin: bool | None = None,
        tls_terminated: bool = False,
        audit_sink: Callable[[Mapping[str, Any]], None] | Any | None = None,
        max_request_bytes: int = MAX_REQUEST_BYTES,
        max_response_bytes: int = DEFAULT_MAX_RESPONSE_BYTES,
        max_concurrent_requests: int = 32,
        rate_limit_per_minute: int = 120,
        session_ttl_seconds: int = 3600,
        request_timeout_seconds: float = 8.0,
    ) -> None:
        if not backend:
            raise ValueError("backend is required")
        if not _is_loopback_host(host) and not tls_terminated:
            raise ValueError(
                "非回环远程 MCP 监听必须明确声明由可信反向代理终止 TLS"
            )
        if audit_sink is None:
            raise ValueError("远程 MCP 必须配置审计 sink；缺失时拒绝启动")
        if not callable(audit_sink) and not callable(getattr(audit_sink, "write", None)):
            raise ValueError("远程 MCP 审计 sink 必须可调用或实现 write")
        self.backend = backend
        self.authenticator = authenticator
        self.host = host
        self.configured_port = int(port)
        self.tls_terminated = bool(tls_terminated)
        self.resource_url = validate_https_endpoint(
            resource_url,
            name="resource_url",
            require_mcp_path=True,
        )
        self.authorization_servers = tuple(
            validate_https_endpoint(item, name="authorization_server")
            for item in authorization_servers
            if item.strip()
        )
        self.allowed_origins = frozenset(
            normalized for normalized in (_normalize_origin(item) for item in allowed_origins) if normalized
        )
        # Native MCP clients (including OpenClaw) may omit Origin.  Validate it
        # whenever supplied, while allowing operators to require it explicitly
        # for browser-only deployments with ``require_origin=True``.
        self.require_origin = bool(require_origin) if require_origin is not None else False
        self.audit_sink = audit_sink
        self.max_request_bytes = max(1024, int(max_request_bytes))
        self.max_response_bytes = max(1024, int(max_response_bytes))
        self.max_concurrent_requests = max(1, int(max_concurrent_requests))
        self.rate_limit_per_minute = max(1, int(rate_limit_per_minute))
        self.session_ttl_seconds = max(60, int(session_ttl_seconds))
        self.request_timeout_seconds = max(0.1, float(request_timeout_seconds))
        self._server: ThreadingHTTPServer | None = None
        self._thread: threading.Thread | None = None
        self._executor = ThreadPoolExecutor(max_workers=self.max_concurrent_requests)
        self._concurrency = threading.BoundedSemaphore(self.max_concurrent_requests)
        self._session_lock = threading.RLock()
        self._sessions: dict[str, _Session] = {}
        self._rate_lock = threading.Lock()
        self._rate: dict[str, deque[float]] = defaultdict(deque)
        self._closed = False

    # ----------------------------------------------------------- policy

    def _check_origin(self, origin: str | None) -> str | None:
        normalized = _normalize_origin(origin) if origin else ""
        if origin and not normalized:
            raise RemoteMcpError("MCP_H_ORIGIN_INVALID", "Origin 无效", status_code=403)
        if normalized:
            if normalized not in self.allowed_origins:
                raise RemoteMcpError("MCP_H_ORIGIN_FORBIDDEN", "Origin 不被允许", status_code=403)
            return normalized
        if self.require_origin:
            raise RemoteMcpError("MCP_H_ORIGIN_REQUIRED", "必须提供受信任的 Origin", status_code=403)
        return None

    def _authenticate(self, authorization: str | None, session_id: str | None) -> AuthenticatedPrincipal:
        try:
            return self.authenticator.authenticate(authorization, session_id=session_id)
        except McpAuthenticationError:
            raise

    def _rate_check(self, subject_id: str) -> None:
        now = time.monotonic()
        with self._rate_lock:
            bucket = self._rate[subject_id]
            while bucket and bucket[0] <= now - 60:
                bucket.popleft()
            if len(bucket) >= self.rate_limit_per_minute:
                raise RemoteMcpError("MCP_H_RATE_LIMITED", "当前用户请求过于频繁", status_code=429)
            bucket.append(now)

    def _evict_sessions(self) -> None:
        cutoff = time.monotonic() - self.session_ttl_seconds
        with self._session_lock:
            for key, value in list(self._sessions.items()):
                if value.last_seen < cutoff:
                    self._sessions.pop(key, None)

    def _new_session(self, principal: AuthenticatedPrincipal) -> tuple[str, _Session]:
        session_id = principal.session_id
        client = RemoteAgentGuardClient(
            self.backend,
            principal,
            audit_sink=self.audit_sink,
            request_timeout_seconds=self.request_timeout_seconds,
        )
        state = _Session(principal, McpServer(client, controlled_demo_tools=False), time.monotonic(), time.monotonic())
        with self._session_lock:
            # A generated ID is random; in the extremely unlikely event of a
            # collision, retry rather than replacing another user's session.
            while session_id in self._sessions:
                principal = AuthenticatedPrincipal(
                    principal.subject,
                    principal.claims,
                    secrets.token_urlsafe(24),
                    principal.client_id,
                    principal.scopes,
                )
                session_id = principal.session_id
                client = RemoteAgentGuardClient(
                    self.backend,
                    principal,
                    audit_sink=self.audit_sink,
                    request_timeout_seconds=self.request_timeout_seconds,
                )
                state = _Session(principal, McpServer(client, controlled_demo_tools=False), time.monotonic(), time.monotonic())
            self._sessions[session_id] = state
        return session_id, state

    def _session_for(
        self,
        principal: AuthenticatedPrincipal,
        session_id: str | None,
        *,
        initialize: bool,
    ) -> tuple[str, _Session, bool]:
        self._evict_sessions()
        if session_id is None:
            if not initialize:
                raise RemoteMcpError("MCP_H_SESSION_REQUIRED", "tools 请求需要 MCP 会话", status_code=400)
            return (*self._new_session(principal), True)
        with self._session_lock:
            state = self._sessions.get(session_id)
            if state is None:
                if not initialize:
                    raise RemoteMcpError("MCP_H_SESSION_NOT_FOUND", "MCP 会话不存在或已过期", status_code=404)
                # Keep the client supplied ID for initialize so OpenClaw can
                # recover from a reconnect deterministically.
                bound = AuthenticatedPrincipal(
                    principal.subject,
                    principal.claims,
                    session_id,
                    principal.client_id,
                    principal.scopes,
                )
                client = RemoteAgentGuardClient(
                    self.backend,
                    bound,
                    audit_sink=self.audit_sink,
                    request_timeout_seconds=self.request_timeout_seconds,
                )
                state = _Session(bound, McpServer(client, controlled_demo_tools=False), time.monotonic(), time.monotonic())
                self._sessions[session_id] = state
                return session_id, state, True
            if not _principal_matches(state.principal, principal):
                raise RemoteMcpError("MCP_H_SESSION_IDENTITY_MISMATCH", "MCP 会话与访问令牌身份不一致", status_code=403)
            state.last_seen = time.monotonic()
            return session_id, state, False

    # ------------------------------------------------------------ protocol

    def _run_message(
        self,
        state: _Session,
        message: Mapping[str, Any],
        request_id: str,
    ) -> dict[str, Any] | None:
        client = state.server.client
        if isinstance(client, RemoteAgentGuardClient):
            with client.request_context(request_id):
                return state.server.handle(message)
        return state.server.handle(message)

    def handle_message(
        self,
        message: Any,
        *,
        authorization_header: str | None,
        origin: str | None = None,
        session_id: str | None = None,
        request_id: str | None = None,
    ) -> tuple[int, dict[str, Any] | None, str | None, str | None]:
        """Process one request for tests and embedding.

        Returns ``(http_status, JSON-RPC response, session_id, CORS origin)``.
        Authentication/origin failures are represented as HTTP-level payloads,
        not JSON-RPC tool errors.
        """

        cors_origin = self._check_origin(origin)
        supplied_session = _session_header(session_id)
        principal = self._authenticate(authorization_header, supplied_session)
        if not isinstance(message, Mapping):
            raise RemoteMcpError("MCP_H_INVALID_JSON", "请求体必须是 JSON 对象", status_code=400)
        rpc_method = message.get("method")
        initialize = rpc_method == "initialize"
        if not isinstance(rpc_method, str):
            raise RemoteMcpError("MCP_H_INVALID_JSONRPC", "缺少 JSON-RPC method", status_code=400)
        self._rate_check(principal.subject_id)
        if not self._concurrency.acquire(blocking=False):
            raise RemoteMcpError("MCP_H_BUSY", "服务当前繁忙，请稍后重试", status_code=429)
        try:
            # Header supplied IDs are operator/client correlation data and are
            # rejected when malformed.  JSON-RPC IDs that are not strings or
            # numbers do not enter audit logs; they receive a fresh internal ID.
            rpc_request_id = _validated_request_id(
                request_id if request_id is not None else message.get("id"),
                supplied_by_header=request_id is not None,
            )
            # Validate the request correlation ID before allocating or mutating
            # a session, so malformed requests cannot create orphan sessions.
            active_session, state, created = self._session_for(principal, supplied_session, initialize=initialize)
            try:
                response = self._executor.submit(self._run_message, state, message, rpc_request_id).result(
                    timeout=self.request_timeout_seconds
                )
            except FutureTimeoutError as exc:
                raise RemoteMcpError("MCP_H_TIMEOUT", "MCP 请求超时，调用未完成", status_code=504) from exc
            return 200, response, active_session, cors_origin
        finally:
            self._concurrency.release()

    # ------------------------------------------------------------- HTTP

    def _error_payload(self, code: str, message: str) -> dict[str, Any]:
        return {"status": "blocked", "reason_code": code, "message": message}

    def readiness(self) -> dict[str, Any]:
        """Combine AgentGuard and remote OIDC readiness, failing closed."""

        probes = getattr(self.backend, "probes", None)
        if probes is not None and callable(getattr(probes, "readiness", None)):
            try:
                payload = copy.deepcopy(dict(probes.readiness()))
            except Exception:
                payload = {
                    "ready": False,
                    "process_alive": True,
                    "dependencies": {},
                    "blocking_dependencies": ["agentguard"],
                    "reason_codes": ["MCP_G002_AGENTGUARD_UNAVAILABLE"],
                    "fail_closed": True,
                }
        else:
            payload = {
                "ready": True,
                "process_alive": True,
                "dependencies": {},
                "blocking_dependencies": [],
                "reason_codes": [],
                "fail_closed": True,
            }

        oidc_healthy, oidc_detail = self.authenticator.readiness()
        dependencies = payload.setdefault("dependencies", {})
        if not isinstance(dependencies, dict):
            dependencies = {}
            payload["dependencies"] = dependencies
        dependencies["remote_oidc"] = {
            "name": "remote_oidc",
            "healthy": oidc_healthy,
            "required": True,
            "detail": oidc_detail,
        }
        blocking = payload.setdefault("blocking_dependencies", [])
        if not isinstance(blocking, list):
            blocking = []
            payload["blocking_dependencies"] = blocking
        if not oidc_healthy and "remote_oidc" not in blocking:
            blocking.append("remote_oidc")
        reasons = payload.setdefault("reason_codes", [])
        if not isinstance(reasons, list):
            reasons = []
            payload["reason_codes"] = reasons
        if not oidc_healthy and "S004_IDENTITY_UNAVAILABLE" not in reasons:
            reasons.append("S004_IDENTITY_UNAVAILABLE")
        payload["ready"] = bool(payload.get("ready", False)) and oidc_healthy and not blocking
        payload.setdefault("process_alive", True)
        payload["fail_closed"] = True
        return payload

    def _handler_class(self) -> type[BaseHTTPRequestHandler]:
        service = self

        class Handler(BaseHTTPRequestHandler):
            protocol_version = "HTTP/1.1"
            server_version = "AgentGuard-Remote-MCP/0.1"
            sys_version = ""

            def _send_bytes(
                self,
                status: int,
                body: bytes,
                *,
                content_type: str = "application/json; charset=utf-8",
                cors_origin: str | None = None,
                extra_headers: Mapping[str, str] | None = None,
            ) -> None:
                self.send_response(status)
                self.send_header("Content-Type", content_type)
                self.send_header("Content-Length", str(len(body)))
                self.send_header("Cache-Control", "no-store")
                if cors_origin:
                    self.send_header("Access-Control-Allow-Origin", cors_origin)
                    self.send_header("Vary", "Origin")
                    self.send_header("Access-Control-Expose-Headers", "Mcp-Session-Id, WWW-Authenticate")
                for key, value in (extra_headers or {}).items():
                    self.send_header(key, value)
                self.end_headers()
                if body:
                    self.wfile.write(body)

            def _send_json(
                self,
                status: int,
                payload: Mapping[str, Any],
                *,
                cors_origin: str | None = None,
                extra_headers: Mapping[str, str] | None = None,
            ) -> None:
                body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"), default=str).encode("utf-8")
                if len(body) > service.max_response_bytes:
                    status = 503
                    body = json.dumps(
                        service._error_payload("MCP_H_RESPONSE_TOO_LARGE", "响应超过安全上限"),
                        ensure_ascii=False,
                        separators=(",", ":"),
                    ).encode("utf-8")
                self._send_bytes(status, body, cors_origin=cors_origin, extra_headers=extra_headers)

            def _origin_for_error(self) -> str | None:
                origin = self.headers.get("Origin")
                try:
                    return service._check_origin(origin)
                except RemoteMcpError:
                    return None

            def do_OPTIONS(self) -> None:  # noqa: N802
                path = urlsplit(self.path).path
                if path != MCP_PATH:
                    self._send_json(404, service._error_payload("MCP_H_NOT_FOUND", "路径不存在"))
                    return
                try:
                    cors = service._check_origin(self.headers.get("Origin"))
                except RemoteMcpError as exc:
                    self._send_json(exc.status_code, service._error_payload(exc.code, str(exc)))
                    return
                self._send_bytes(
                    204,
                    b"",
                    cors_origin=cors,
                    extra_headers={
                        "Allow": "GET, POST, OPTIONS",
                        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
                        "Access-Control-Allow-Headers": "Authorization, Content-Type, Mcp-Session-Id, Mcp-Protocol-Version, X-Request-ID",
                    },
                )

            def do_GET(self) -> None:  # noqa: N802
                path = urlsplit(self.path).path
                if path in {"/healthz", "/health"}:
                    self._send_json(200, {"status": "ok", "service": "remote-mcp"})
                    return
                if path == "/readyz":
                    payload = service.readiness()
                    self._send_json(200 if payload.get("ready") else 503, payload)
                    return
                if path in {"/.well-known/oauth-protected-resource/mcp", "/.well-known/oauth-protected-resource"}:
                    self._send_json(
                        200,
                        protected_resource_metadata(
                            service.resource_url,
                            service.authorization_servers,
                            scopes_supported=(service.authenticator.required_scope,),
                        ),
                    )
                    return
                if path != MCP_PATH:
                    self._send_json(404, service._error_payload("MCP_H_NOT_FOUND", "路径不存在"))
                    return
                try:
                    cors = service._check_origin(self.headers.get("Origin"))
                    session = _session_header(self.headers.get("Mcp-Session-Id"))
                    # GET establishes the server-to-client event stream.  It
                    # does not execute a tool; clients can subsequently POST
                    # JSON-RPC messages to the same endpoint.
                    principal = service._authenticate(self.headers.get("Authorization"), session)
                    if session:
                        with service._session_lock:
                            state = service._sessions.get(session)
                            if state is None:
                                raise RemoteMcpError("MCP_H_SESSION_NOT_FOUND", "MCP 会话不存在或已过期", status_code=404)
                            if not _principal_matches(state.principal, principal):
                                raise RemoteMcpError("MCP_H_SESSION_IDENTITY_MISMATCH", "MCP 会话与访问令牌身份不一致", status_code=403)
                            state.last_seen = time.monotonic()
                    payload = f"event: endpoint\ndata: {MCP_PATH}\n\n".encode("utf-8")
                    self._send_bytes(
                        200,
                        payload,
                        content_type="text/event-stream; charset=utf-8",
                        cors_origin=cors,
                        extra_headers={"Connection": "keep-alive"},
                    )
                except McpAuthenticationError as exc:
                    headers = {"WWW-Authenticate": exc.challenge} if exc.challenge else None
                    self._send_json(exc.status_code, service._error_payload(exc.code, str(exc)), extra_headers=headers)
                except RemoteMcpError as exc:
                    self._send_json(exc.status_code, service._error_payload(exc.code, str(exc)))

            def do_POST(self) -> None:  # noqa: N802
                path = urlsplit(self.path).path
                if path != MCP_PATH:
                    self._send_json(404, service._error_payload("MCP_H_NOT_FOUND", "路径不存在"))
                    return
                content_type = self.headers.get("Content-Type", "")
                media_type = content_type.split(";", 1)[0].strip().lower()
                if media_type != "application/json":
                    self._send_json(
                        415,
                        service._error_payload(
                            "MCP_H_CONTENT_TYPE_UNSUPPORTED",
                            "MCP POST 必须使用 application/json",
                        ),
                    )
                    return
                content_encoding = self.headers.get("Content-Encoding", "").strip().lower()
                if content_encoding and content_encoding != "identity":
                    self._send_json(
                        415,
                        service._error_payload(
                            "MCP_H_CONTENT_ENCODING_UNSUPPORTED",
                            "MCP 请求不支持压缩编码",
                        ),
                    )
                    return
                protocol_version = self.headers.get("Mcp-Protocol-Version", "").strip()
                if protocol_version and protocol_version not in SUPPORTED_PROTOCOL_VERSIONS:
                    self._send_json(
                        400,
                        service._error_payload(
                            "MCP_H_PROTOCOL_VERSION_UNSUPPORTED",
                            "MCP 协议版本不受支持",
                        ),
                    )
                    return
                try:
                    length = int(self.headers.get("Content-Length", "0"))
                except ValueError:
                    self._send_json(400, service._error_payload("MCP_H_CONTENT_LENGTH_INVALID", "Content-Length 无效"))
                    return
                if length <= 0 or length > service.max_request_bytes:
                    self._send_json(
                        413 if length > service.max_request_bytes else 400,
                        service._error_payload("MCP_H_REQUEST_TOO_LARGE", "请求体为空或超过安全上限"),
                    )
                    return
                try:
                    cors = service._check_origin(self.headers.get("Origin"))
                    raw = self.rfile.read(length)
                    message = json.loads(raw.decode("utf-8"))
                    request_id = self.headers.get("X-Request-ID") or self.headers.get("Mcp-Request-ID")
                    status, response, session, _ = service.handle_message(
                        message,
                        authorization_header=self.headers.get("Authorization"),
                        origin=self.headers.get("Origin"),
                        session_id=self.headers.get("Mcp-Session-Id"),
                        request_id=request_id,
                    )
                    headers = {"Mcp-Session-Id": session} if session else {}
                    if response is None:
                        self._send_bytes(202, b"", cors_origin=cors, extra_headers=headers)
                    else:
                        self._send_json(status, response, cors_origin=cors, extra_headers=headers)
                except UnicodeDecodeError:
                    self._send_json(400, service._error_payload("MCP_H_INVALID_ENCODING", "请求体必须是 UTF-8"))
                except json.JSONDecodeError:
                    self._send_json(400, service._error_payload("MCP_H_INVALID_JSON", "请求体不是合法 JSON"))
                except McpAuthenticationError as exc:
                    headers = {"WWW-Authenticate": exc.challenge} if exc.challenge else None
                    self._send_json(exc.status_code, service._error_payload(exc.code, str(exc)), extra_headers=headers)
                except RemoteMcpError as exc:
                    self._send_json(exc.status_code, service._error_payload(exc.code, str(exc)))
                except Exception:
                    # No stack traces or exception text cross the network.
                    self._send_json(503, service._error_payload("MCP_H_INTERNAL_FAIL_CLOSED", "MCP 请求未执行"))

            def log_message(self, *_: Any) -> None:
                return

        return Handler

    def start(self) -> "StreamableHttpMcpServer":
        if self._server is not None:
            return self
        self._server = ThreadingHTTPServer((self.host, self.configured_port), self._handler_class())
        self._server.daemon_threads = True
        self._thread = threading.Thread(target=self._server.serve_forever, name="remote-mcp-http", daemon=True)
        self._thread.start()
        return self

    @property
    def port(self) -> int:
        return int(self._server.server_address[1]) if self._server is not None else self.configured_port

    @property
    def base_url(self) -> str:
        return f"http://{self.host}:{self.port}"

    def serve_forever(self) -> None:
        self.start()
        assert self._thread is not None
        try:
            while self._thread.is_alive():
                self._thread.join(timeout=0.5)
        except KeyboardInterrupt:
            pass
        finally:
            self.close()

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        if self._server is not None:
            self._server.shutdown()
            self._server.server_close()
            self._server = None
        if self._thread is not None:
            self._thread.join(timeout=3)
            self._thread = None
        self._executor.shutdown(wait=False, cancel_futures=True)

    def __enter__(self) -> "StreamableHttpMcpServer":
        return self.start()

    def __exit__(self, *_: Any) -> None:
        self.close()


# Short aliases make the embedding API discoverable without weakening the
# explicit ``StreamableHttp`` name used in deployment documentation.
McpHttpServer = StreamableHttpMcpServer
RemoteMcpServer = StreamableHttpMcpServer


__all__ = [
    "MCP_PATH",
    "McpHttpServer",
    "RemoteAgentGuardClient",
    "RemoteMcpError",
    "RemoteMcpServer",
    "StreamableHttpMcpServer",
]
